import { globalGoals } from './module-global_goals';
import { globalMultiCookieSetup } from './module-global_multi_cookie_setup';
import { globlaAiSetup } from './module-global_ai_setup';
import { globalPersoSegment } from './module-global_perso_segments';
import { globalGoalsForSegments } from './module-global_goals_for_segments';
import { globalSegmentsRemarketingAndReach } from './module-global_segments_reach_remarketing';
import { T23SchnappchenjagerCase2 } from './module-158000_T23_Schnaeppchenjäger_Case2';
import { T21UmbennenWerbenVerdienen } from './module-171090_T21_Umbennen_Werben_Verdienen';
import { P09ReduktionBSPAllnetMundL } from './module-95823_P09_Reduktion_BSP_Allnet_M_und_L';
import { T15GlueckwunschbannerWK2Iteration } from './module-179600_T15_v2_Glueckwunschbanner_WK_2_Iteration';

globalGoals();
globalMultiCookieSetup();
globlaAiSetup();
globalPersoSegment();
globalGoalsForSegments();
globalSegmentsRemarketingAndReach();
T23SchnappchenjagerCase2();
T21UmbennenWerbenVerdienen();
P09ReduktionBSPAllnetMundL();
T15GlueckwunschbannerWK2Iteration();
